name: Copy to s3
description: copy files to s3

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  deployToS3:
    runs-on: ubuntu-latest
    steps:
      - name: authenticate in aws
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::569170436432:role/GitHubActionsDeployRole

      - name: show env vars
        run: echo 'printenv'

      - name: verify aws role
        run: aws sts get-caller-identity
        
      - name: fetch files
        uses: actions/checkout@v6.0.2

      - name: upload files
        run: aws s3 sync ./data s3://github-vit100/data/
          
  
